export const GET_SCHEDULE_ASYNC_REQUEST = "GET_CURRENCIES_ASYNC_REQUEST";

export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAILURE = "GET_SCHEDULE_FAILURE";
export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST";

export const SET_SCHEDULE = "SET_SCHEDULE";
